(function(){
"use strict";
const $=id=>document.getElementById(id),input=$("documentInput"),message=$("inputMessage"),run=$("runReport");
let importedDocument=null;
const sample=`Recent research shows that formative feedback improves student writing (Bader et al., 2019). Earlier work also reviewed major approaches to data clustering (Jain et al., 1999).

References
Bader, M., Burner, T., Hoem Iversen, S., & Varga, Z. (2019). Student perspectives on formative feedback as part of writing portfolios. Assessment & Evaluation in Higher Education, 44(7), 1017–1028. https://doi.org/10.1080/02602938.2018.1564812

Jain, A. K., Murty, M. N., & Flynn, P. J. (1999). Data clustering: A review. ACM Computing Surveys, 31(3), 264–323. https://doi.org/10.1145/331499.331504`;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function step(name,status,label){const e=document.querySelector(`[data-step="${name}"]`);e.className="pipe-step "+status;e.querySelector("em").textContent=label;}
function progress(n){$("progressFill").style.width=n+"%";}
function sections(){return CitationReferenceSplitter.splitDocumentSections(input.value);}
function refs(){const s=sections();return CitationReferenceSplitter.splitReferences(s.references).filter(x=>x.length>15);}
function stats(){const r=refs();$("inputStats").textContent=input.value.trim()?`${sections().found?"已定位参考文献区":"按参考文献列表处理"} · ${r.length} 条`:"等待输入";}
function issueCards(items,empty){return items.length?items.map(x=>`<div class="issue-card ${/缺失|不匹配/.test(x.tag)?"missing":""}"><h4>${esc(x.tag)}${x.page?`<span class="source-page">原文第 ${esc(x.page)} 页</span>`:""}</h4>${x.quote?`<blockquote>${esc(x.quote)}</blockquote>`:""}<div class="issue-actions"><div class="desc">${esc(x.desc)}</div>${x.quote?`<button type="button" class="locate-source" data-quote="${esc(x.quote)}">定位原文</button>`:""}</div></div>`).join(""):`<div class="empty">✓ ${empty}</div>`;}
function locateOriginal(quote){const start=input.value.indexOf(quote);if(start<0){message.textContent="未能在当前输入中定位该原文，内容可能已被修改。";message.className="message error";return;}input.focus();input.setSelectionRange(start,start+quote.length);const before=input.value.slice(0,start),line=before.split("\n").length-1,total=Math.max(1,input.value.split("\n").length-1);input.scrollTop=Math.max(0,(input.scrollHeight-input.clientHeight)*(line/total)-input.clientHeight*.25);input.closest(".input-card")?.scrollIntoView({behavior:"smooth",block:"start"});message.textContent="已在输入框中选中对应原文。";message.className="message";}
function bindLocateButtons(){document.querySelectorAll(".locate-source").forEach(button=>button.addEventListener("click",()=>locateOriginal(button.dataset.quote||"")));}
function renderDistribution(data){const target=$("distributionResults");target.innerHTML="";data.forEach((section,i)=>{const card=document.createElement("section");card.className="distribution-card";card.innerHTML=`<div class="distribution-head"><span>${String(i+1).padStart(2,"0")}</span><div><h4>${esc(section.title)}</h4><p>${esc(section.subtitle)}</p></div></div><div class="distribution-list"></div>`;const list=card.querySelector(".distribution-list"),max=Math.max(1,...section.items.map(x=>x.count));section.items.forEach((x,j)=>{const row=document.createElement("div");row.className="distribution-item";row.innerHTML=`<span class="distribution-rank">${j+1}</span><span class="distribution-label">${esc(x.label)}</span><span class="distribution-track"><i></i></span><strong>${x.count}</strong>`;row.querySelector("i").style.width=Math.max(6,Math.round(x.count/max*100))+"%";list.appendChild(row);});if(!section.items.length)list.innerHTML='<div class="empty">暂无统计数据</div>';target.appendChild(card);});}
function renderVerification(results){$("verifyResults").innerHTML=results.map((r,i)=>`<article class="result ${r.status}"><h4>REF #${i+1} · ${r.status==="matched"?"✓ 已匹配":"需复核"} · ${r.score}%</h4><div class="orig-quote"><span>原文引用</span><p>${esc(r.original)}</p></div>${r.error?`<div class="error-box">${esc(r.error)}</div>`:`<table><thead><tr><th>字段</th><th>来源原信息</th><th>核验结论</th></tr></thead><tbody>${r.checks.map(x=>`<tr><td>${esc(x.label)}</td><td>${esc(x.value)}</td><td><span class="field-status ${x.status}">${x.status==="match"?"✓":"不一致"}</span></td></tr>`).join("")}</tbody></table><div class="evidence"><span>证据来源</span><b>${esc(r.sources.join(" · "))}</b></div>${r.record?.url?`<a class="source-link" href="${esc(r.record.url)}" target="_blank" rel="noreferrer">查看来源记录 ↗</a>`:""}`}</article>`).join("");}
function summary(refCount,local,verification){const review=verification.filter(x=>x.status!=="matched").length,matched=verification.length-review;$("summaryCards").innerHTML=`<div class="summary-card"><span>参考文献</span><b>${refCount}</b><em>统一切分后的条目</em></div><div class="summary-card"><span>全文与格式问题</span><b>${local.fullIssues.length+local.formatIssues.length}</b><em>建议逐项复核</em></div><div class="summary-card"><span>来源需复核</span><b>${review}</b><em>${matched} 条已匹配</em></div><div class="summary-card"><span>不同文中引用</span><b>${new Set(local.citations.map(c=>`${c.authors?.[0]?.surname}|${c.year}`)).size}</b><em>按作者与年份合并</em></div>`;return{review};}
async function generate(){const s=sections(),r=refs();if(!input.value.trim()||!r.length){message.textContent="请先输入含参考文献的内容。";message.className="message error";return;}run.disabled=true;message.className="message";message.textContent="正在生成综合报告…";$("pipeline").hidden=false;$("report").hidden=true;step("full","active","正在检查");step("format","","等待");step("verification","","等待");step("distribution","","等待");progress(5);try{await new Promise(x=>setTimeout(x,0));const useImported=importedDocument&&importedDocument.referenceBlocks?.length===r.length,local=CitationReportEngine.localAnalysis(s.body,r,useImported?importedDocument.referenceBlocks:null,useImported?importedDocument.bodyBlocks:null);$("fullResults").innerHTML=issueCards(local.fullIssues,"未发现全文引用一致性问题。");step("full","done",`完成 · ${local.fullIssues.length} 项`);progress(22);step("format","active","正在检查");$("formatResults").innerHTML=issueCards(local.formatIssues,"未发现参考文献格式问题。");bindLocateButtons();step("format","done",`完成 · ${local.formatIssues.length} 项`);progress(42);step("verification","active","正在连接公开索引");const verification=await CitationReportEngine.verifyAll(r,(done,total)=>step("verification","active",done<total?`正在核验 ${done+1} / ${total}`:"整理结果"));renderVerification(verification);const sum=summary(r.length,local,verification);step("verification","done",`完成 · ${sum.review} 条需复核`);progress(78);step("distribution","active","正在统计");renderDistribution(CitationReportEngine.distribution(local));step("distribution","done","完成");progress(100);$("report").hidden=false;message.textContent=`报告已生成：${r.length} 条参考文献，${local.fullIssues.length+local.formatIssues.length} 项本地问题，${sum.review} 条来源需复核。`;}catch(e){message.textContent="生成报告失败："+(e.message||e);message.className="message error";}finally{run.disabled=false;}}
async function importWord(){const file=$("wordFile").files?.[0];if(!file)return;const isPdf=/\.pdf$/i.test(file.name||"")||file.type==="application/pdf";message.textContent="正在本地读取 "+file.name+" …";message.className="message";try{const result=isPdf?await CitationPdfImporter.parse(file,(page,total)=>{message.textContent=`正在本地解析 PDF：${page} / ${total} 页…`;}):await CitationReportEngine.parseDocx(file);importedDocument=result;input.value=result.text;stats();message.textContent=isPdf?`PDF 已在本地解析完成，共 ${result.pageCount} 页；格式检查已读取字体和页码信息。`:`Word 文档已在本地解析完成${result.footnoteCount?`，已读取 ${result.footnoteCount} 条脚注`:""}。`;try{localStorage.setItem("cr_current_file",file.name);}catch(_){}}catch(e){message.textContent=(isPdf?"PDF":"Word")+" 导入失败："+(e.message||e);message.className="message error";try{localStorage.removeItem("cr_current_file");}catch(_){}}$("wordFile").value="";}
window.CitationReportPage=Object.freeze({applyWorkspaceDocument(documentData){importedDocument=documentData||null;input.value=documentData?.fullText||[documentData?.bodyText,documentData?.referencesText].filter(Boolean).join("\n\nReferences\n");stats();}});
input.addEventListener("input",()=>{importedDocument=null;stats();});$("loadSample").addEventListener("click",()=>{importedDocument=null;input.value=sample;stats();});$("clearInput").addEventListener("click",()=>{importedDocument=null;input.value="";stats();$("report").hidden=true;});$("importWord").addEventListener("click",()=>$("wordFile").click());$("wordFile").addEventListener("change",importWord);run.addEventListener("click",generate);$("printReport").addEventListener("click",()=>window.print());stats();
})();
